### ISSUE TITLE
Missing licence notice file?

### ISSUE THREAD

**Issue by ivo-kolev** [loki4j/loki-logback-appender#103]
Hi,

The binary distribution/jar of loki-logback-appender absorbs code from Grafana Loki and Google Protobuf. One of the sources (https://github.com/loki4j/loki-logback-appender/blob/main/common/src/main/java/com/dslplatform/json/RawJsonWriter.java) has a copyright from " Nova Generacija Softvera d.o.o".

Shouldn't this be explicitly listed in a NOTICE file with their licences and copyright holder?

Cheers, Ivo Kolev

**Comment by nehaev** [comment]
Hi!

Thanks for reporting this! It's a valid question. I don't have much expertise in how to arrange this legal stuff properly. Probably, we should stick with some common practice (how it's done in well-established java projects). 

Not sure I will have a time to investigate this in the nearest future. But for sure I will be glad to accept a PR fixing this.

**Comment by ivo-kolev** [comment]
Hi Anton,

Thanks for the prompt reply. Unfortunately I can't contribute directly, but the notice file would be like below. Looking in the binary distro and the source there is one source and Google Protobuf that are absorbed; I figured out that the com.grafana.loki is produced upon the protobuf definition and its not actual Loki code. The file is usually labelled NOTICE and resides next to the LICENCE file. Its good both to be included in the binary distro, so that the clients of Loki Logback Appender have certainty what's inside. You may consider adding copyright header "Copyright (c) 2020, loki4j" in the lib own source too.

Cheers, Ivo Kolev

NOTICE suggested content:

Loki Logback Appender, Copyright 2020, Loki4j

This software includes the following third-party software modules:

1) Source RawJsonWriter.java
Copyright (c) 2015, Nova Generacija Softvera d.o.o.
Licensed under BSD-3-Clause, https://opensource.org/licenses/BSD-3-Clause

2) Protocol Buffers - Google's data interchange format
Copyright 2008 Google Inc.  All rights reserved.
https://developers.google.com/protocol-buffers/
Licensed under BSD-3-Clause, https://opensource.org/licenses/BSD-3-Clause

**Comment by ivo-kolev** [comment]
Sorry, I just realized that the google package is also a protobuf generated and not the actual library. So the notice should only credit "Nova Generacija Softvera d.o.o.".

Cheers, Ivo Kolev
