### ISSUE TITLE
The current releases are not JPMS-compatible

### ISSUE THREAD

**Issue by zalavaari** [loki4j/loki-logback-appender#122]
The current releases of the `loki-logback-appender` contains all of the dependencies, therefore it cannot be used in a modular Java 11+ project because of package collisions.

Is it possible to provide another `loki-logback-appender` artifact, which contains only the project's own files?

The `loki-logback-appender` can be JPMS-compatible even without a proper `module-info.java`, if these dependencies won't be in the jar.

**Comment by nehaev** [comment]
The fix was published in v1.3.0-rc1 ([release page](https://github.com/loki4j/loki-logback-appender/releases/tag/v1.3.0-rc1)). Feel free to re-open this ticket or create a new one in case of any issues.

**Comment by zalavaari** [comment]
I've just noticed that the relevant dependencies (grpc for example) are missing from the pom.
Anyway, thank you for the fix!
