### ISSUE TITLE
Add exponential backoff and jitter to the retries

### ISSUE THREAD

**Issue by acm19** [loki4j/loki-logback-appender#194]
Current retries are constant which might cause snowball effect if many client get rate limited at the same time. Retries should have a exponential backoff and jitter to avoid this.

**Comment by nehaev** [comment]
Hi @acm19, and thanks again for posting this. I totally agree that exponential backoff and jitter for retries is good to have.

**Comment by acm19** [comment]
Hey @nehaev, I might try to find some time to give this a try but I wonder what your thoughts are about the implementation. I see two options, either we give only exponential retries as retry mechanism (we can then add a validation for `maxRetries` and `retryTimeoutMs` so that they don't overflow `long`) or we give different retries options. The second option would probably involve adding a lib and a few more properties. I kind of feel the first option should be enough, but it will break backward compatibility. Other thoughts? Preferences?

**Comment by nehaev** [comment]
Hey @acm19,

I think having only exponential backoff retries is fine. 

We can introduce two more config options: `minRetryTimeoutMs` and `maxRetryTimeoutMs`. Also we can deprecate `retryTimeoutMs`, see the [example](https://github.com/loki4j/loki-logback-appender/pull/140/files). Looks like this deprecation would be the only compatibility break. Of course, it still requires a major version increment and starting the 1.5.x series, but I don't see any issues with that.

**Comment by acm19** [comment]
Hey @nehaev, I've created a proposal. I think it's fine to leave the current config settings, I just updated the documentation. Please take a look and let me know your thoughts.
