### ISSUE TITLE
Allow truncation of log lines to the a max size

### ISSUE THREAD

**Issue by acm19** [loki4j/loki-logback-appender#195]
Loki has a [maximum item](https://grafana.com/docs/grafana-cloud/send-data/logs/) size of 64KB. This is configurable for self hosted instances but they still [recommend a maximum](https://grafana.com/docs/loki/latest/operations/request-validation-rate-limits/#line_too_long) of 256KB.

It's sometimes hard to predict the size of certain log lines. But losing them is often not desire. Therefore, it'd be great to have the option to truncate them to a set size limit.

Promtail does it as part of their [limit_config](https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#limits_config) via:
* `max_line_size`
* `max_line_size_truncate`

**Comment by nehaev** [comment]
Hi @acm19, thanks for posting this!

Log line truncation can be done inside Logback pattern itself using `%.-n` and explicit stack trace limit: 

```xml
<message>
        <pattern>l=%level h=${HOSTNAME} c=%logger{20} t=%thread | %.-1000msg %ex{300}</pattern>
</message>
```

Theoretically, it should be enough to cover all the viable use cases with line size limits. If there is anything outstanding, feel free to re-open.

**Comment by acm19** [comment]
Thanks for this, I was thinking of the metrics that could be generated out of this by the appender. But I think it's workaroundable by filtering, so I'll try this.
