### ISSUE TITLE
[Enhancement request] Support for auth "Authorization: Basic xxx"

### ISSUE THREAD

**Issue by patpatpat123** [loki4j/loki-logback-appender#202]
Hello team,

I just wanted to reach out asking if it is possible to support auth of type  "Authorization: Basic xxx"

As of right now, we can use auth with username and password as follow:

```
    <appender name="LOKI" class="com.github.loki4j.logback.Loki4jAppender">
        <http>
            <url>https://xxx.grafana.net/loki/api/v1/push</url>
            <auth>
                <username>aaa</username>
                <password>bbb</password>
            </auth>
        </http>
```

While this is working great, could you please help support this very common construct to grafana?

```
    <appender name="LOKI" class="com.github.loki4j.logback.Loki4jAppender">
        <http>
            <url>https://xxx.grafana.net/loki/api/v1/push</url>
            <auth>
                <Authorization>Basic ODAzNzU2OmdsY19leUp2SWpvaU1UQXdNek16TWlJc0ltNGlPaUowWlhOMFptOTFjaTEwWlhOMFptOTFj</Authorization>
            </auth>
        </http>
```

Thank you

**Comment by nehaev** [comment]
Hey @patpatpat123, could you please add in your enhancement request the following:

- Explanation why this enhancement would be useful to most Loki4j users
- List of some other Loki clients (or Logback appenders) where this enhancement exists

**Comment by patpatpat123** [comment]
Hello @nehaev ,

Thank you for your answer.

Sure, please allow me to clarify. 
When one uses grafana cloud, with Loki in particular, but with traces and metrics in mind, user will do:

In order to connect to grafana cloud prometheus back end, for metrics, one needs the url, as well as the token via 
```
https://prometheus-prod-xx-prod-us-east-0.grafana.net/api/prom/push
--header 'Authorization: Basic MTMzODk [...] ZYMD0='
```
Where the Basic is derived from username and password, but user only needs to configure the auth basic (one element, not username and passwords, two elements)

Of course, the argument can be made username and password can be added as well.

```
https://someusername:somepassword@prometheus-prod-xx-prod-us-east-0.grafana.net/api/prom/push
```
But basically, with a regular open telemetry client or prometheus client, it is possible, there is the option to configure only the host and the authorization basic header, without having to maintain the whole username password pair.

Same for tracing with tempo, one can use the token:
```
https://tempo-prod-xx-prod-us-east-0.grafana.net
--header 'Authorization: Basic MTMzODk [...] ZYMD0='
```

And again, the argument can be made username and password can be used.
```
https://someusername:somepassword@tempo-prod-xx-prod-us-east-0.grafana.net
```

This allow the client, using any regular open tracing client to maintain just the url and the authorization basic header

However, with the current version of loki, while on grafana cloud backend, it is possible to pass in either username password pair, or just an authorization basic, this client limits users giving the possibility to only pass in the username and password pair.

A possible would be to allow loki users, which some of them are grafana cloud user, to give the possibility to use:

```
 <http>
            <url>https://xxx.grafana.net/loki/api/v1/push</url>
            <auth>
                <Authorization>Basic ODAzNzU2OmdsY19leUp2SWpvaU1UQXdNek16TWlJc0ltNGlPaUowWlhOMFptOTFjaTEwWlhOMFptOTFj</Authorization>
            </auth>
        </http>
```

Hence, maintaining only auth basic, and not a username password pair.

**Comment by nehaev** [comment]
Well, auth basic token is literally username+password (see https://github.com/loki4j/loki-logback-appender/blob/main/loki-client/src/main/java/com/github/loki4j/client/http/HttpConfig.java#L60), so it's the same maintenance efforts and security level.

**Comment by KafkaProServerless** [comment]
@nehaev Upvoting this. I have the same need. 
Our team only deals with the basic token, not the combination of username and password.
Can this ```<auth> <Authorization>``` be supported?
