### ISSUE TITLE
请问loki是否能支持log4j2的框架配置？

### ISSUE THREAD

**Issue by a123665404** [loki4j/loki-logback-appender#203]
如题，由于我们系统日志框架为log4j2，log4j2配置的http的appender，但是想到loki的maven包是logback的，引用后有兼容性问题，不知道如何进行适配，如能支持，能否出具示例。

**Comment by nehaev** [comment]
Hi @a123665404, this project has no relation to log4j2, only to logback.

**Comment by a123665404** [comment]
ok ， thank you !
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Anton ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年12月19日 17:17
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            Theresa ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [loki4j/loki-logback-appender] 请问loki是否能支持log4j2的框架配置？ (Issue #203)
        
      
    
  

Hi @a123665404, this project has no relation to log4j2, only to logback.
