### ISSUE TITLE
Labels should drop the label that with empty value

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [loki4j/loki-logback-appender#207]
```
<label>
  <pattern>job_id=%mdc{LOG_JOB_ID}</pattern>
</label>
```
In my code, the `job_id` is only set in some method and in the other method it is blank. But the appender only handle it when it is set some value or it will throw exception. The exception make all logs not send to loki.
https://github.com/loki4j/loki-logback-appender/blob/f3a17b2ddab6d5fb66af0db8abf43609a41eb295/loki-logback-appender/src/main/java/com/github/loki4j/logback/AbstractLoki4jEncoder.java#L246

**Comment by nehaev** [comment]
Hi @lanyuanxiaoyao, thanks for reporting this!

Right, neither label name nor label value can be empty string. It's not explicitly stated in the docs, so I will update them.

You can easily fix this by providing a default value:

```xml
<label>
  <pattern>job_id=%mdc{LOG_JOB_ID:-none}</pattern>
</label>
```

**Comment by lanyuanxiaoyao** [comment]
> Hi @lanyuanxiaoyao, thanks for reporting this!
> 
> Right, neither label name nor label value can be empty string. It's not explicitly stated in the docs, so I will update them.
> 
> You can easily fix your code by providing a default value:
> 
> ```
> <label>
>   <pattern>job_id=%mdc{LOG_JOB_ID:-none}</pattern>
> </label>
> ```
> 
> As for dropping a label in case of empty value, it's hard to distinguish between "intentionally" empty label and unexpected parsing error (e.g. wrong property reference, incorrect key-value separator, etc.) In later case silently dropping a label could be a headache for a user. So I guess the requirement to provide a default for optional label values is a good tradeoff.

Thanks for answer.
Maybe it provide a option called `ignoreBlankValue` would be nice.
