### ISSUE TITLE
Memory issue when labels change quite often (on every log request)

### ISSUE THREAD

**Issue by ZIRAKrezovic** [loki4j/loki-logback-appender#222]
I have been debugging a memory issue and pinned it finally to loki-logback-encoder. Lets start with my analysis

My memory heap dump (relevant part only)

![image](https://github.com/loki4j/loki-logback-appender/assets/145535273/79b95055-aa63-4510-87b9-55f723463f76)

Loki appender related in: java.util.String

![image](https://github.com/loki4j/loki-logback-appender/assets/145535273/338394b2-57a0-4c7a-a46b-e7baba7fee5c)

LogStream holds the most entries for HashMap usage, mainly the labels which are different on every send

![image](https://github.com/loki4j/loki-logback-appender/assets/145535273/7bd19727-fe51-4907-8f26-e2efc7fe23ff)

Final holder is the UnboundAtomicMapCache instantiated in AbstractLoki4jEncoder.

![image](https://github.com/loki4j/loki-logback-appender/assets/145535273/94f8fab2-7407-4c58-b07a-f5b4663dbb42)

Due to nature of trace id being virtually different in every log message, cache miss is guaranteed and creation of new node on every new log request

![image](https://github.com/loki4j/loki-logback-appender/assets/145535273/1a495eee-540a-4c08-8acb-d1293c0ebfa2)

This cache will grow indefinitely and never free unused labels, resulting in application eventually dying with out of memory error with any heap limit and a certain amount of logs.

Finally, my logback-spring.xml snippet

```
    <springProfile name="logLoki">
        <appender name="LOKI" class="com.github.loki4j.logback.Loki4jAppender">
            <http>
                <url>${lokiHost}</url>
                <tenantId>${lokiTenantId}</tenantId>
                <auth>
                    <username>${lokiUserName}</username>
                    <password>${lokiPassword}</password>
                </auth>
            </http>
            <format>
                <label>
                    <pattern>application=${appName},hostname=${HOSTNAME},traceId=%X{traceId:-NONE},level=%level,vendor=ZIRA</pattern>
                </label>
                <message>
                    <pattern>${FILE_LOG_PATTERN}</pattern>
                </message>
                <sortByTime>true</sortByTime>
            </format>
        </appender>

        <root level="INFO">
            <appender-ref ref="LOKI" />
        </root>
    </springProfile>
```

Now, I had the issue where loki would reject the logs due to label difference, so I had otel-exporter strip the traceId field and could probably drop it here. But still, the memory issue should be fixed or users should be aware of it, at least. That's why I am creating this (more of an FYI) report.

I am using loki-logback-appender 1.4.2 with spring-boot 3.2.3

**Comment by nehaev** [comment]
Hi @ZIRAKrezovic, thanks for reporting this! I guess you're right, even in extreme cases like this, the default cache implementation shouldn't lead to OOM. However, there is always a tradeoff as the current implementation is simple, performant, and covers all the sane use cases.  I'll see what I can do to improve it.

As a workaround, you can check a [setting](https://loki4j.github.io/loki-logback-appender/docs/configuration#format-settings) `format.label.streamCache` that allows you to customize a cache implementation used for streams. You can either use advanced libs like Caffeine or omit caching completely.

Probably you know, but still, I have to notice, that your use case with too many unique streams goes strictly against Loki's [best practices](https://grafana.com/docs/loki/latest/get-started/labels/bp-labels).

**Comment by nehaev** [comment]
Some relevant experiments from the past: https://github.com/loki4j/loki-logback-appender/compare/main...limited-stream-cache
