### ISSUE TITLE
Support for adding structured metadata

### ISSUE THREAD

**Issue by ZIRAKrezovic** [loki4j/loki-logback-appender#225]
Hi, is it possible to add support for sending structured metadata in addition to labels?

https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/

It's an experimental feature, but promtail already supports it and it would be nice if loki-logback-appender supported it as well.

Thanks in advance

**Comment by nehaev** [comment]
Hi @ZIRAKrezovic, thanks for reporting this! Yeah, it would be nice to add this feature.
