### ISSUE TITLE
[Enhancement request] Possibility to send loki logs to loki, but also to kafka

### ISSUE THREAD

**Issue by KafkaProServerless** [loki4j/loki-logback-appender#228]
Hello team,

This project is very useful for sending logs to loki backend.

Would it be possible to add an option to send logs to loki, but also to send the same logs to kafka for post-processing?

Thank you for considering this enhancement request.

**Comment by nehaev** [comment]
Hi @KafkaProServerless, thanks for reporting this! This project is a log appender to Loki only. Kafka is out of the scope.
