### ISSUE TITLE
Loki: grpc: received message larger than max

### ISSUE THREAD

**Issue by nehaev** [loki4j/loki-logback-appender#24]
Warning for Loki's log:

```
{"log":"level=warn ts=2020-11-19T09:50:51.424307286Z caller=logging.go:62 traceID=79d770bca7a1231d msg=\"POST /loki/api/v1/push (500) 77.922341ms Response: \\\"rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4673517 vs. 4194304)\\\\n\\\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 4771412; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.9 (Java/11.0.8); \"\n","stream":"stderr","time":"2020-11-19T09:50:51.424439852Z"}
```

**Comment by nehaev** [comment]
Workaround.

Default max message size is defined in Loki config:

```
server:
  # 4MB
  grpc_server_max_recv_msg_size: 4194304
```

You can increase it:

```
server:
  # 8MB
  grpc_server_max_recv_msg_size: 8388608
```

**Comment by tautvydasvalasinas** [comment]
I'm also having the same issue, however I believe that the encoders causing the problems as the message is perpetually resent and somehow doubles in size. At least on InteliJ I'm seeing a lot of additional endline symbol escape apptems that eventually fills the message limit like so:
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\r\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\r\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n

**Comment by nehaev** [comment]
@tautvydasvalasinas Could you please provide your loki4j appender configuration from `logback.xml`? What version of loki4j are you using? You're running it on Windows, right?

**Comment by tautvydasvalasinas** [comment]
Hi, yes I'm using windows. Here's my configuration. My loki instance is running on local docker (running image grafana/loki:1.6.0) with default configuration. I'm using gradle:
```
plugins {
	id 'org.springframework.boot' version '2.2.0.RELEASE'
	id 'io.spring.dependency-management' version '1.0.8.RELEASE'
	id 'java'
}

group = 'logging.loki'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '8'

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'io.micrometer:micrometer-registry-prometheus'
	implementation 'com.github.loki4j:loki-logback-appender-jdk8:0.4.0'
	compile 'org.apache.httpcomponents:httpclient:4.5.13'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
}

test {
	useJUnitPlatform()
}
```

And here's my logback config:
```
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%date %level [%thread] %logger{10} [%file:%line] %msg%n</pattern>
        </encoder>
    </appender>
    <appender name="LOKI" class="com.github.loki4j.logback.LokiApacheHttpAppender">
        <url>http://localhost:3100/loki/api/v1/push</url>
        <batchSize>100</batchSize>
        <batchTimeoutMs>10000</batchTimeoutMs>
        <encoder class="com.github.loki4j.logback.JsonEncoder">
            <label>
                <pattern>app=loki-demo,host=${HOSTNAME},level=%level</pattern>
                <pairSeparator>,</pairSeparator>
                <keyValueSeparator>=</keyValueSeparator>
                <nopex>true</nopex>
            </label>
            <message>
                <pattern>JAVA8 l=%level h=${HOSTNAME} c=%logger{20} t=%thread | %msg %ex</pattern>
            </message>

            <sortByTime>true</sortByTime>
        </encoder>
        <maxConnections>1</maxConnections>
        <connectionKeepAliveMs>120000</connectionKeepAliveMs>
    </appender>

    <root level="debug">
        <appender-ref ref="STDOUT"/>
        <appender-ref ref="LOKI"/>
    </root>
</configuration>
```

Hopefully this helps!

**Comment by nehaev** [comment]
@tautvydasvalasinas 
Tried to reproduce you case with this [test](https://github.com/loki4j/loki-logback-appender/blob/main/src/test/java/com/github/loki4j/logback/AbstractLoki4jAppenderTest.java#L94), but it works correctly even on [jdk8/windows](https://github.com/loki4j/loki-logback-appender/blob/main/.github/workflows/compatibility-tests.yaml#L45). If I'm still missing something, feel free to PR a test that reproduces you issue.

**Comment by nehaev** [comment]
Closing this in favor of #48.

If escaping problem (`\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\r`) is reproduced, this should be a separate issue.
