### ISSUE TITLE
License url is wrong

### ISSUE THREAD

**Issue by deatechgithub** [loki4j/loki-logback-appender#252]
https://github.com/loki4j/loki-logback-appender/blob/master/LICENSE.md this points to a 404 page
But it actually should point to: https://github.com/loki4j/loki-logback-appender/blob/main/LICENSE

**Comment by nehaev** [comment]
Hi @deatechgithub! Sorry, but given this description I'm unable understand neither the issue you're facing, nor the way it could be potentially solved.

**Comment by danielz1983** [comment]
Sorry, i am adding more infos now.

I am using the license-maven-plugin and when i am downloading the licenses the plugin fails with

```
[INFO] --- license:2.4.0:download-licenses (default-cli) @ efnol ---
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
[ERROR] 'https://github.com/loki4j/loki-logback-appender/blob/master/LICENSE.md' returned 404 Not Found 
```

As the url to the license.md is just pointing to the wrong place
