### ISSUE TITLE
feature-request: Allow setting format.message.mdc.fieldName to an empty string.

### ISSUE THREAD

**Issue by apollo13** [loki4j/loki-logback-appender#264]
I'd love to set `format.message.mdc.fieldName` to an empty string. I have tried setting it to `<fieldName></fieldName>` but I am still ending up with an `mdc_` prefix. Did I get the config wrong or is it not possible to unset the prefix completely?

**Comment by nehaev** [comment]
Thanks for reporting this, @apollo13!

Looks like logback configuration system (joran) ignores empty values. Probably we would need to introduce a special property to signal that no prefix is needed.
