### ISSUE TITLE
Does Loki work with native images?

### ISSUE THREAD

**Issue by marcingrzejszczak** [loki4j/loki-logback-appender#266]
Hey, thanks for the great project :)

I've recently published a blog post on the [Spring Blog](https://spring.io/blog/2024/10/28/lets-use-opentelemetry-with-spring) and I've created the [following code](https://github.com/marcingrzejszczak/observability-boot-blog-post) to back it up.

The problem is that when the two applications are running together as native images the logs are not being shown in Loki. I haven't debugged this much though but maybe it's a known issue for Loki appender?

**Comment by nehaev** [comment]
Hi @marcingrzejszczak, thanks for reporting this! It's really good to know there are blog posts mentioning Loki4j project.

I'm unaware of any issues regarding native images and haven't tried them myself. 

However, I can take a look into this, if you send me any related exceptions, stack traces, or at least an instruction how to build and run your sample project as a native image.

**Comment by marcingrzejszczak** [comment]
Say no more :) https://github.com/marcingrzejszczak/observability-boot-blog-post/blob/main/BLOG.adoc#running-it-all-together-with-aot-support

**Comment by patpatpat123** [comment]
Hello, upvoting this. I am also trying to make Loki work with native image.

**Comment by nehaev** [comment]
I've checked GraalVM docs. Looks like for reflection-heavy libs (such as logback) so-called "reachability-metadata" should be provided.

There is a community project [graalvm-reachability-metadata](https://github.com/oracle/graalvm-reachability-metadata) where you can publish and share a metadata for a lib. Currently it seems like even the support for logback (which is an upstream project to this one) is sub-optimal: the metadata is published only for 3 outdated versions. So I re-direct you to that project.

I tend to close this issue as it's out-of-scope for Loki4j. It's not about improving the Loki4j codebase, it's about gathering and maintaining some metadata for Loki4j and probably for logback as well. And this is definitely a separate project that I would rather leave up to the community.

Feel free to correct me if I got something wrong.
