### ISSUE TITLE
Label filters service_name created, without apparet configuration

### ISSUE THREAD

**Issue by patpatpat123** [loki4j/loki-logback-appender#273]
Hello,

Just wanted to reach out to point out an issue.

I am using this library to send logs to Loki, the grafana cloud version of it.

Here is the logback-spring.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="true">
    
    <springProperty name="name" source="spring.application.name" />

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>
                %d{yyyy-MM-dd HH:mm:ss} ${PID} %-5level --- [%thread] [${name},%X{traceId:-},%X{spanId:-}] %logger{36} : %msg%n
            </pattern>
        </encoder>
    </appender>

    <appender name="LOKI" class="com.github.loki4j.logback.Loki4jAppender">
        <metricsEnabled>true</metricsEnabled>
        <http>
            <url>https://logs-prod-017.grafana.net/loki/api/v1/push</url>
            <auth>
                <username>821111</username>
                <password>abc</password>
            </auth>
        </http>
        <format>
            <label>
                <pattern>name=${name},host=${HOSTNAME},level=%level,pid=${PID},thread=%thread</pattern>
                <readMarkers>true</readMarkers>
            </label>
            <message>
                <pattern>
{
    "message":"%message"
}
                </pattern>
            </message>
            <sortByTime>true</sortByTime>
        </format>
        <verbose>false</verbose>
    </appender>

    <root level="INFO">
        <appender-ref ref="STDOUT"/>
        <appender-ref ref="LOKI"/>
    </root>

</configuration>

```

It works fine actually, but:
As you can see, there is no reference of service_name here.

However, on grafana cloud loki side, I can see service_name (please see screenshot to confirm)
<img width="1194" alt="Screenshot 2024-11-25 at 22 08 36" src="https://github.com/user-attachments/assets/52adf9e9-2fe8-4fcf-9742-684a67f6640f">

The issue is, how would this field which I am not configuring end up in grafana cloud?

How to send similar, for instance, service_namespace?

Thank you for your help on this issue

**Comment by nehaev** [comment]
Hi @patpatpat123, 

> As you can see, there is no reference of service_name here.

`service_name` is [added on Loki side](https://grafana.com/docs/loki/latest/setup/upgrade/#service_name-label). As far as I know, you can disable it for standalone Loki, but not for Grafana Cloud.

> How to send similar, for instance, service_namespace?

If it's low-cardinality value (to me it looks as one), you can simply pass it as a label.

**Comment by patpatpat123** [comment]
Thank you for the answer @nehaev .

But for the low cardinality value, it seems we cannot add "dot"

19:46:30,135 |-ERROR in com.github.loki4j.client.pipeline.AsyncBufferPipeline@54fc4112 - Loki responded with non-success status 400 on batch #4c35a0923024bf (112,003 bytes). Error: couldn't parse labels: 1:101: parse error: unexpected character inside braces: '.'
```
 <format>
            <label>
                <pattern>name=${name},host=${HOSTNAME},level=%level,pid=${PID},thread=%thread,service_namespace=${namespace}</pattern>
                <readMarkers>true</readMarkers>
            </label>```
            
Is this error expected? If yes, how can I send a label with a "dot" with this library?

**Comment by nehaev** [comment]
@patpatpat123 I'm not sure where the "dot" comes from. In case it's not sorted out yet, feel free to file a separate issue on this, with a proper description.
