### ISSUE TITLE
[Enhancement request] Support for something similar to <JsonTemplateLayout> in Loki logback appender

### ISSUE THREAD

**Issue by patpatpat123** [loki4j/loki-logback-appender#274]
Hello there,

Just wanted to reach out with a small enhancement request.

In log4j2 world, there is something very famous called the JsonTemplate (and its newer version JsonTemplateLayout)
https://logging.apache.org/log4j/2.x/manual/json-template-layout.html

This allows the sending of **custom structured** JSON logs to the backend.

For loki logback, the documentation refered many times to 
```
            <message>
                <pattern>
                </pattern>
            </message>
```

But we cannot just bake in a custom JsonTemplateLayout.

Would it be possible for this project to accommodate custom json template?

Thank you

**Comment by nehaev** [comment]
Hi @patpatpat123, thanks for reporting this! Currently the customization of JSON is supposed to be done via [Custom JSON providers](https://loki4j.github.io/loki-logback-appender/docs/jsonlayout#custom-json-providers). Is there any use case not covered by this?

**Comment by nehaev** [comment]
Closing as no clarification provided.
