### ISSUE TITLE
Limit max batch size in bytes

### ISSUE THREAD

**Issue by nehaev** [loki4j/loki-logback-appender#48]
Add an option to limit max batch size in bytes. This could prevent issues like #24

**Comment by ArchangelX360** [comment]
That would be awesome as Loki host on Grafana Cloud has a pretty aggressive limitation of 65536 Bytes!

**Comment by joffrey-bion** [comment]
Yes it would be really great! We currently had to put a `batchSize` of 1 to be able to handle our biggest logs, but this means that little logs get sent one-by-one now, which is not ideal.

**Comment by nehaev** [comment]
Work on this feature is now in progress, mostly in [this](https://github.com/loki4j/loki-logback-appender/compare/main...batch-size-check-2) branch. Hopefully, I will be able to come up with a reliable implementation in the nearest future, so this can be included into 1.1.0 release. Otherwise, I will have to postpone it to next releases.

**Comment by nehaev** [comment]
Some preparations for this are done in 1.1.0, but the complete implementation is not there yet. Postponing to 1.2.0.

**Comment by ArchangelX360** [comment]
@nehaev Thanks for adding this 🙏 , any ETA on `1.2.0`?

**Comment by nehaev** [comment]
Hey @ArchangelX360! A release candidate for `1.2.0` should be out within a few days, and a release will follow in about a week after that if no bugs reported.

**Comment by ArchangelX360** [comment]
Thank you for the release 🙏🏼

**Comment by nehaev** [comment]
Thanks for using Loki4j! Please let me know if there are any issues or things need to be improved.
