### ISSUE TITLE
Add support for sending tenantId to Loki

### ISSUE THREAD

**Issue by nehaev** [loki4j/loki-logback-appender#65]
Loki4j lacks a multi-tenancy support.

We should be able to configure `tenantId` in `logback.xml`:

```xml
<appender name="LOKI" class="com.github.loki4j.logback.Loki4jAppender">
    <http>
        <url>http://localhost:3100/loki/api/v1/push</url>
        <tenantId>customer1<tenantId>
        ...
    </http>
    ...
</appender>
```

If `tenantId` is specified, Loki4j should send it to Loki in header `X-Scope-OrgID`, as described in [docs](https://grafana.com/docs/loki/latest/operations/multi-tenancy/).

PR #56 can be used as a source of inspiration on how to add headers and how to write an integration test for this.

Please drop a comment if you'd like to prepare a PR for this.

**Comment by ramazanyich** [comment]
Thanks for fast response! 
Have one concern with solution: 
It looks good for small amount of tenants which are static.
In our case we can have many tenants (currently about 50, but we will have more of them...) and they are dynamic (can be added/removed). 
So I see two issues: 
first - static config, but that one we can manage as we construct our loki4j appender using our internal code (not xml config).
second - is the resources usage. Per http sender there is a http thread pool currently in Loki4j. So if there are 100 tenants then it is already at least 100 threads... and that number is growing with number of tenants.. We use just one Loki server which will be configured for multi-tenancy, so one thread pool with some decent amount of threads should be enough. Just header should be changing during log record sending. 
that second concern is kind of hitting..

**Comment by nehaev** [comment]
@ramazanyich this is rather technical task. Let's keep the discussion of your particular case in #64.

**Comment by ramazanyich** [comment]
@nehaev will it be possible to make a release of loki4j ? we want to use tenantId parameter   in our project.

**Comment by nehaev** [comment]
@ramazanyich Preparing a full-fledged release will take some time, but I [released](https://github.com/loki4j/loki-logback-appender/releases/tag/v1.1.0-m1) current master state as `1.1.0-m1` so you can try it out.

**Comment by ramazanyich** [comment]
thanks Anton !
